### ISSUE TITLE
cannot load such file -- hotcell/lexerc

### ISSUE THREAD

**Issue by flash-gordon** [pyromaniac/hotcell#2]
Hi, I got error!

What I did:

```
echo "gem 'hotcell'" >> Gemfile
bundle
gem list | grep hotcell # hotcell (0.2.0)
bundle exec rspec
```

And BOOM!

```
gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- hotcell/lexerc (LoadError)
    from gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in require'
    from gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
    from gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
    from gems/hotcell-0.2.0/lib/hotcell.rb:19:in `<top (required)>'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from gems/combustion-0.5.1/lib/combustion.rb:24:in `initialize!'
    from spec/spec_helper.rb:37:in `<top (required)>'
    from gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:867:in `require'
    from gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:867:in `block in setup_load_path_and_require'
    from gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:867:in `each'
    from gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:867:in `setup_load_path_and_require'
    from gems/rspec-core-2.14.5/lib/rspec/core/configuration_options.rb:25:in `configure'
    from gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:21:in `run'
    from gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:80:in `run'
    from gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:17:in `block in autorun'
```

If I edit hotcell.rb and just change

``` ruby
require 'hotcell/lexerc'
```

to

``` ruby
require 'lexerc'
```

it works.

I think the problem probably somewhere in C extension.

**Comment by flash-gordon** [comment]
Mac OS X 10.8.5

**Comment by pyromaniac** [comment]
Try the new version

**Comment by flash-gordon** [comment]
It works, great!
